const { writeFile } = require('fs');
const writeFileUsingFS = (targetPath, environmentFileContent) => {
  writeFile(targetPath, environmentFileContent, (err) => {
    if (err) {
      console.log(err);
    }
    if (environmentFileContent !== '') {
      console.log(`wrote variables to ${targetPath}`);
    }
  });
};
const target = './src/environments/environment.prod.ts';
const environmentFileContent = `
  // This file was autogenerated by dynamically running ${process.argv[1]}
  export const environment = {
    production: ${true},
    api_key: '${process.env.API_KEY}',
  };
`;

writeFileUsingFS(target, environmentFileContent);
